version: "3"
services:
    postgres:
        image: "postgres:12"
        environment: 
            # These variables should be defined in a .env file
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports: 
            - "5432:5432"
