// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPeer struct {
	UserFName *string `json:"userFName"`
	UserLName *string `json:"userLName"`
	Hostname  string  `json:"hostname"`
	PublicKey string  `json:"publicKey"`
	AllowedIP string  `json:"allowedIp"`
}

type Peer struct {
	UserFName       *string `json:"userFName"`
	UserLName       *string `json:"userLName"`
	ID              string  `json:"id"`
	PublicKey       string  `json:"publicKey"`
	Hostname        string  `json:"hostname"`
	AllowedIP       string  `json:"allowedIp"`
	Endpoint        *string `json:"endpoint"`
	LatestHandshake *int    `json:"latestHandshake"`
	TransferRxBytes *int    `json:"transferRxBytes"`
	TransferTxBytes *int    `json:"transferTxBytes"`
}
