// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPeer struct {
	Name      string `json:"name"`
	PublicKey string `json:"publicKey"`
	AllowedIP string `json:"allowedIp"`
}

type Peer struct {
	ID              string  `json:"id"`
	PublicKey       string  `json:"publicKey"`
	Name            string  `json:"name"`
	AllowedIP       string  `json:"allowedIp"`
	Endpoint        *string `json:"endpoint"`
	LatestHandshake *string `json:"latestHandshake"`
	TransferRxBytes *int    `json:"transferRxBytes"`
	TransferTxBytes *int    `json:"transferTxBytes"`
}
